# XcodeGen Project Specification for Speakez
# Generate with: xcodegen generate

name: Speakez

options:
  bundleIdPrefix: com.speakez
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    PRODUCT_NAME: Speakez
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "13.0"
    CODE_SIGN_STYLE: Automatic
    ENABLE_HARDENED_RUNTIME: YES
    INFOPLIST_FILE: Speakez/Info.plist
    CODE_SIGN_ENTITLEMENTS: Speakez/Speakez.entitlements
    SWIFT_OBJC_BRIDGING_HEADER: Speakez/Speakez-Bridging-Header.h

targets:
  Speakez:
    type: application
    platform: macOS
    sources:
      - path: Speakez
        excludes:
          - "**/*.md"
          - "**/*.yml"
          - "**/*Tests*"
    settings:
      base:
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        LD_RUNPATH_SEARCH_PATHS: "@executable_path/../Frameworks"
        COMBINE_HIDPI_IMAGES: YES
        ENABLE_PREVIEWS: YES
        # Disable sandbox for accessibility API
        ENABLE_APP_SANDBOX: NO
        # Header search paths - use Frameworks folder
        HEADER_SEARCH_PATHS:
          - "$(PROJECT_DIR)/Frameworks/whisper"
        # Library search paths - use Frameworks folder
        LIBRARY_SEARCH_PATHS:
          - "$(PROJECT_DIR)/Frameworks/whisper"
        # Link against required frameworks and libraries
        OTHER_LDFLAGS:
          - "-framework"
          - "Carbon"
          - "-framework"
          - "AVFoundation"
          - "-framework"
          - "CoreAudio"
          - "-framework"
          - "ApplicationServices"
          - "-framework"
          - "Accelerate"
          - "-framework"
          - "Metal"
          - "-framework"
          - "MetalKit"
          - "-lwhisper"
          - "-lggml"
          - "-lggml-base"
          - "-lggml-cpu"
          - "-lggml-metal"
          - "-lggml-blas"
          - "-lc++"
      configs:
        Debug:
          SWIFT_OPTIMIZATION_LEVEL: "-Onone"
          DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
        Release:
          SWIFT_OPTIMIZATION_LEVEL: "-O"
          SWIFT_COMPILATION_MODE: wholemodule
          DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
    info:
      path: Speakez/Info.plist
      properties:
        LSUIElement: true
        NSMicrophoneUsageDescription: "Speakez needs access to your microphone to transcribe your speech to text."
    entitlements:
      path: Speakez/Speakez.entitlements
      properties:
        com.apple.security.app-sandbox: false
        com.apple.security.device.audio-input: true
        com.apple.security.network.client: true

  SpeakezTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: SpeakezTests
    settings:
      base:
        INFOPLIST_FILE: SpeakezTests/Info.plist
        BUNDLE_LOADER: "$(TEST_HOST)"
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Speakez.app/Contents/MacOS/Speakez"
    dependencies:
      - target: Speakez

schemes:
  Speakez:
    build:
      targets:
        Speakez: all
        SpeakezTests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - SpeakezTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
